# Generated by Django 2.0.4 on 2021-06-10 11:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='uploaded_images/scoop_1.jpg', null=True, upload_to='uploaded_images', verbose_name='image'),
        ),
    ]
