# Generated by Django 2.0.4 on 2021-04-01 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 13, 18, 44, 56539), help_text='Day of the event', verbose_name='Day of the event'),
        ),
    ]
