# Generated by Django 2.0.4 on 2021-06-10 11:57

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-day']},
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(default=datetime.datetime(2021, 6, 10, 12, 57, 46, 309536), help_text='Day of the event', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='scoop_1.jpg', null=True, upload_to='uploaded_images', verbose_name='image'),
        ),
    ]
