# Generated by Django 3.1.4 on 2022-01-19 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210610_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['day']},
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 1, 19, 13, 2, 19, 151839), help_text='Day of the event', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='forest-of-spruce.jpg', null=True, upload_to='uploaded_images', verbose_name='image'),
        ),
    ]
