# Generated by Django 3.1.4 on 2022-02-11 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220119_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 2, 11, 17, 14, 45, 346630), help_text='Day of the event', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default_woodland.jpg', null=True, upload_to='uploaded_images', verbose_name='image'),
        ),
    ]
