# Generated by Django 3.1.4 on 2022-02-10 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220119_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 2, 10, 17, 30, 12, 431734), help_text='Day of the event', verbose_name='Day of the event'),
        ),
    ]
