"""
Django settings for forest_site project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

import dotenv


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Initiate related env class
#env = dotenv.Env()

# Take environment variables from .env.dev file
#env.Env.read_env(os.path.join(BASE_DIR, '.env')


# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'r236=e_a(%kv3@_+39cl#dws^@fd+iq@k%ls7=ct+58m)sszr='
        #'cg#p$g+j9tax!#a3cup@1$8obt2_+&k3q+pmu)5%asj6yjpkag'


SECRET_KEY = [os.environ.get('SECRET_KEY')]

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = os.getenv('DEBUG', '') != 'False'



#ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS')
# str(os.getenv('ALLOWED_HOSTS'))
ALLOWED_HOSTS = [str(os.getenv('ALLOWED_HOSTS'))]
#print("hosts here "+hosts)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'main_site',
    'blog',
    'events',
    'tinymce',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'forest_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["forest_site/templates/"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'events.custom_context_processor.latest_e',
                'blog.custom_context_processor.latest_news',
                'forest_site.custom_context_processor.get_current_year_to_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'forest_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "forest_site/static"),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Base url to serve media files
#MEDIA_URL = '/static/'

# Path where media is stored
MEDIA_ROOT = os.path.join(BASE_DIR, 'forest_site/static')

#True to avoid transmitting the CSRF cookie over HTTP accidentally
CSRF_COOKIE_SECURE = True
#True to avoid transmitting the session cookie over HTTP accidentally
SESSION_COOKIE_SECURE = True